11. Merchant Item Create
z-fitch/little-shop-7 pull request #75
Opened 2023-07-30 17:22 UTC by z-fitch

11. Merchant Item Create

As a merchant
When I visit my items index page
I see a link to create a new item.
When I click on the link,
I am taken to a form that allows me to add item information.
When I fill out the form I click ‘Submit’
Then I am taken back to the items index page
And I see the item I just created displayed in the list of items.
And I see my item was created with a default status of disabled.

__x__ Wrote Tests __x__ Implemented __x__ Reviewed

Neccesary checkmarks:

    [x] All Tests are Passing

    [x] The code will run locally

Type of change

    [x] New feature
    [] Bug Fix

Implements/Fixes:

    Adds a create item closes #73

Check the correct boxes

    [x] This broke nothing
    [] This broke some stuff
    [] This broke everything

Testing Changes

    [x] No Tests have been changed
    [] Some Tests have been changed
    [] All of the Tests have been changed(Please describe what in the world happened)

Checklist:

    [x] My code has no unused/commented out code
    [x] I have reviewed my code
    [x] I have commented my code, particularly in hard-to-understand areas
    [x] I have fully tested my code

(REQUIRED)Please Include a link to a gif of your feelings about this branch

Link: https://media.giphy.com/media/xkmNi280NkrcY/giphy.gif

2023-07-30 19:02 UTC, JorjaF approved these changes
Just a couple of suggestions but they are not critical so I am going to approve. also i think you did a really good job of testing your enable/disable

2023-07-30 19:02 UTC, JorjaF commented on app/models/item.rb
> +  end
This is a more canonical way to do a where clause in Rails
```suggestion
  def self.enabled_items
    where(status: 1)
  end

  def self.disabled_items
    where(status: 0)
  end
```

2023-07-30 19:02 UTC, JorjaF commented on config/routes.rb
> +    resources :items, only: [:index, :show, :edit, :update, :new, :create], controller: "merchant_items"
Would this be easier because delete is the only function we don't have?
```suggestion
    resources :items, except: [:delete], controller: "merchant_items"
```

2023-07-30 19:06 UTC, Daniel-Gallagher92 commented on config/routes.rb
I remember from the lesson on advanced routes that it's better to use "only:" for some reason, but at this point, I'm curious what everybody thinks about trying an "except" in some of our routes?

2023-07-30 19:06 UTC, Daniel-Gallagher92 approved these changes

2023-07-30 21:05 UTC, ethanrossblack requested changes
resolve merge conflicts

2023-07-30 21:53 UTC, ethanrossblack approved these changes

2023-07-31 04:21 UTC, ethanrossblack commented on app/views/merchant_items/new.html.erb
> +<h2>New Item Form</h2>
Add the header for the new form page?

2023-07-31 04:23 UTC, ethanrossblack requested changes
Honestly, the closing `</h4>` tag was the only thing I saw really _needed_ a change.

You could also throw in the header at the top of the new item page.

Otherwise good code!

2023-07-31 04:23 UTC, ethanrossblack commented on app/views/merchant_items/index.html.erb
> +  <h4><%= link_to "Create Item", new_merchant_item_path(@merchant, @item) %>
missing a closing `</h4>` tag.

2023-07-31 04:23 UTC, ethanrossblack commented on spec/features/merchants/items/index_spec.rb
> +  end
Great testing!

2023-07-31 15:46 UTC, z-fitch commented
I also added the header to the edit item form as well!

2023-07-31 17:22 UTC, ethanrossblack approved these changes
let's roll!

2023-07-31 17:22 UTC, merged